name = "dream-nursery-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "dream-nursery-db"
database_id = "55d8e494-18e3-4971-b98f-33cbec4ad75f"

[[durable_objects.bindings]]
name = "DREAM_ROOM"
class_name = "DreamRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DreamRoom"]
