name = "dream-nursery-api"
main = "index.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "NURSERY", class_name = "Nursery" }
]

[[migrations]]
tag = "v1"
new_classes = ["Nursery"]
